name: Tests

on: push

jobs:
  my-job:
    name: hello-world
    runs-on: ubuntu-20.04
    steps:
    - name: Say hello world
      run: |
        echo Welcome to the Github Actions workshop !

  unit-test:
    name: unit-test
    runs-on: ubuntu-20.04
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    - name: Run unit-test
      run: |
        make tests_run
    - name: Get Coverage
      run: |
        make coverage